### metadata
POST http://localhost:4004/odata/v4/educational/createInDetailsTable
Content-Type: application/json

{
"psid":"20312919"
}

### metadata
POST http://localhost:4004/odata/v4/educational/sendEmail
Content-Type: application/json

{
"to":"palagulla.ramireddy@ltimindtree.com",
"subject":"text",
"body":"text body"
}

### metadata
GET http://localhost:4004/odata/v4/educational/$metadata

### metadata
GET http://localhost:4004/odata/v4/educational/Educational_Details

### metadata
GET http://localhost:4004/odata/v4/educational/SH_Institutes/$count

### metadata
POST http://localhost:4004/odata/v4/educational/SH_InstitutesHANA
Content-Type: application/json

{

}

### metadata
GET http://localhost:4004/odata/v4/educational/Educational_Details?$filter=psid eq '10012553'

### metadata
PUT http://localhost:4004/odata/v4/educational/Educational_Details('93507a59-ac00-4d3b-84a7-e2f465abd583')
Content-Type: application/json

{
"PSID":"111111","course":"SSC6","qualificationSubType":"SSC6","educationCertificate":"10","branch1":"","branch2":"","yearOfPassing":2000,"institution":"ABC","boardOrUniversity":"","courseType":"","duration":"","percentage":"8.2","cgpa":"7.2","division":"","grade":"","status":"D","dmsfoldername":"Y","ismodified":"Y"
}

### metadata
POST http://localhost:4004/odata/v4/educational/Educational_Details
Content-Type: application/json

{
"PSID":"333333","course":"SSC6","qualificationSubType":"SSC6","educationCertificate":"10","branch1":"","branch2":"","yearOfPassing":2000,"institution":"ABC","boardOrUniversity":"","courseType":"","duration":"","percentage":"8.2","cgpa":"7.2","division":"","grade":"","status":"D","dmsfoldername":"Y","ismodified":"Y"
}
